2019-04-20 09:49:54,012 INFO     setup_logging done
2019-04-20 09:50:04,101 INFO     slept enough
2019-04-20 09:50:04,103 INFO     Waiting for RFCOMM connection!!!
2019-04-20 10:10:06,894 INFO     client_sock
2019-04-20 10:10:06,895 INFO     <bluetooth.bluez.BluetoothSocket object at 0x7095ed10>
2019-04-20 10:10:06,896 INFO     client_info
2019-04-20 10:10:06,896 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 10:10:06,898 INFO     slept enough
2019-04-20 10:10:06,899 INFO     Waiting for RFCOMM connection!!!
2019-04-20 10:10:07,218 INFO     Entered threaded client
2019-04-20 10:10:25,443 INFO     Received sensorData
2019-04-20 10:10:25,444 INFO     Getting sensor values
2019-04-20 10:10:26,447 INFO     
entered while loop in thread
2019-04-20 10:10:26,451 INFO     
new value sent:
2019-04-20 10:10:26,452 INFO     realtime
-2.96 2.403 -0.473
2019-04-20 10:10:27,754 INFO     
entered while loop in thread
2019-04-20 10:10:27,758 INFO     
new value sent:
2019-04-20 10:10:27,759 INFO     realtime
-3.021 2.335 -0.458
2019-04-20 10:10:29,061 INFO     
entered while loop in thread
2019-04-20 10:10:29,065 INFO     
new value sent:
2019-04-20 10:10:29,066 INFO     realtime
-2.983 2.365 -0.534
2019-04-20 10:10:30,368 INFO     
entered while loop in thread
2019-04-20 10:10:30,372 INFO     
new value sent:
2019-04-20 10:10:30,373 INFO     realtime
-2.968 2.396 -0.473
2019-04-20 10:10:31,676 INFO     
entered while loop in thread
2019-04-20 10:10:31,679 INFO     
new value sent:
2019-04-20 10:10:31,680 INFO     realtime
-3.029 2.373 -0.458
2019-04-20 10:10:32,983 INFO     
entered while loop in thread
2019-04-20 10:10:32,986 INFO     
new value sent:
2019-04-20 10:10:32,987 INFO     realtime
-2.998 2.426 -0.587
2019-04-20 10:10:34,290 INFO     
entered while loop in thread
2019-04-20 10:10:34,293 INFO     
new value sent:
2019-04-20 10:10:34,294 INFO     realtime
-2.96 2.365 -0.526
2019-04-20 10:10:35,597 INFO     
entered while loop in thread
2019-04-20 10:10:35,600 INFO     
new value sent:
2019-04-20 10:10:35,601 INFO     realtime
-3.021 2.335 -0.397
2019-04-20 10:10:35,806 ERROR    Unhandled exception in thread started by
2019-04-20 10:10:35,807 ERROR    <function threaded_bt at 0x70940300>
2019-04-20 10:10:35,808 ERROR    Traceback (most recent call last):
2019-04-20 10:10:35,809 ERROR      File "uus.py", line 215, in threaded_bt
2019-04-20 10:10:35,811 ERROR    realtime_object.stoprequest()
2019-04-20 10:10:35,812 ERROR    TypeError
2019-04-20 10:10:35,813 ERROR    :
2019-04-20 10:10:35,814 ERROR    'bool' object is not callable
2019-04-20 10:10:36,904 INFO     
entered while loop in thread
2019-04-20 10:10:36,907 INFO     
new value sent:
2019-04-20 10:10:36,908 INFO     realtime
-2.998 2.449 -0.511
2019-04-20 10:10:38,211 INFO     
entered while loop in thread
2019-04-20 10:10:38,214 INFO     
new value sent:
2019-04-20 10:10:38,215 INFO     realtime
-3.029 2.487 -0.42
2019-04-20 10:10:39,518 INFO     
entered while loop in thread
2019-04-20 10:10:39,521 INFO     
new value sent:
2019-04-20 10:10:39,522 INFO     realtime
-3.052 2.434 -0.534
2019-04-20 10:10:40,825 INFO     
entered while loop in thread
2019-04-20 10:10:40,829 INFO     
new value sent:
2019-04-20 10:10:40,830 INFO     realtime
-3.044 2.48 -0.511
2019-04-20 10:10:42,132 INFO     
entered while loop in thread
2019-04-20 10:10:42,145 INFO     
new value sent:
2019-04-20 10:10:42,146 INFO     realtime
-2.991 2.449 -0.557
2019-04-20 10:10:43,449 INFO     
entered while loop in thread
2019-04-20 10:10:43,452 INFO     
new value sent:
2019-04-20 10:10:43,453 INFO     realtime
-2.998 2.403 -0.557
2019-04-20 10:10:44,756 INFO     
entered while loop in thread
2019-04-20 10:10:44,759 INFO     
new value sent:
2019-04-20 10:10:44,760 INFO     realtime
-2.975 2.434 -0.565
2019-04-20 10:10:46,063 INFO     
entered while loop in thread
2019-04-20 10:10:46,077 ERROR    Exception in thread Thread-2:
Traceback (most recent call last):
  File "<string>", line 3, in send
_bluetooth.error: (104, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "uus.py", line 55, in get_realtime_data
    self.conn.send(response_acc)
  File "<string>", line 5, in send
bluetooth.btcommon.BluetoothError: (104, 'Connection reset by peer')
2019-04-20 10:13:33,631 ERROR    Traceback (most recent call last):
2019-04-20 10:13:33,632 ERROR      File "uus.py", line 268, in <module>
2019-04-20 10:13:33,635 ERROR    main()
2019-04-20 10:13:33,635 ERROR      File "uus.py", line 182, in main
2019-04-20 10:13:33,638 ERROR    accept_connection(server_sock)
2019-04-20 10:13:33,638 ERROR      File "uus.py", line 260, in accept_connection
2019-04-20 10:13:33,641 ERROR    client_sock, client_info = server_sock.accept()
2019-04-20 10:13:33,642 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 167, in accept
2019-04-20 10:13:33,647 ERROR    client, addr = self._sock.accept ()
2019-04-20 10:13:33,648 ERROR    KeyboardInterrupt
2019-04-20 10:13:33,650 ERROR    Exception ignored in:
2019-04-20 10:13:33,651 ERROR    <__main__.LoggerHelper object at 0x7095ef70>
2019-04-20 10:13:33,652 ERROR    AttributeError
2019-04-20 10:13:33,653 ERROR    :
2019-04-20 10:13:33,653 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-20 10:13:37,943 INFO     setup_logging done
2019-04-20 10:13:48,026 INFO     slept enough
2019-04-20 10:13:48,027 INFO     Waiting for RFCOMM connection!!!
2019-04-20 10:13:58,485 INFO     client_sock
2019-04-20 10:13:58,486 INFO     <bluetooth.bluez.BluetoothSocket object at 0x70a2fd10>
2019-04-20 10:13:58,487 INFO     client_info
2019-04-20 10:13:58,487 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 10:13:58,488 INFO     slept enough
2019-04-20 10:13:58,490 INFO     Waiting for RFCOMM connection!!!
2019-04-20 10:13:58,809 INFO     Entered threaded client
2019-04-20 10:14:09,108 INFO     Received sensorData
2019-04-20 10:14:09,109 INFO     Getting sensor values
2019-04-20 10:14:10,112 INFO     
entered while loop in thread
2019-04-20 10:14:10,116 INFO     
new value sent:
2019-04-20 10:14:10,117 INFO     realtime
-3.105 2.38 -0.534
2019-04-20 10:14:11,420 INFO     
entered while loop in thread
2019-04-20 10:14:11,423 INFO     
new value sent:
2019-04-20 10:14:11,424 INFO     realtime
-2.945 2.38 -0.58
2019-04-20 10:14:12,727 INFO     
entered while loop in thread
2019-04-20 10:14:12,731 INFO     
new value sent:
2019-04-20 10:14:12,732 INFO     realtime
-3.052 2.373 -0.534
2019-04-20 10:14:14,035 INFO     
entered while loop in thread
2019-04-20 10:14:14,039 INFO     
new value sent:
2019-04-20 10:14:14,040 INFO     realtime
-2.96 2.472 -0.641
2019-04-20 10:14:15,342 INFO     
entered while loop in thread
2019-04-20 10:14:15,346 INFO     
new value sent:
2019-04-20 10:14:15,347 INFO     realtime
-3.006 2.388 -0.572
2019-04-20 10:14:16,650 INFO     
entered while loop in thread
2019-04-20 10:14:16,654 INFO     
new value sent:
2019-04-20 10:14:16,655 INFO     realtime
-2.968 2.426 -0.565
2019-04-20 10:14:17,958 INFO     
entered while loop in thread
2019-04-20 10:14:17,962 INFO     
new value sent:
2019-04-20 10:14:17,963 INFO     realtime
-2.991 2.388 -0.595
2019-04-20 10:14:19,266 INFO     
entered while loop in thread
2019-04-20 10:14:19,270 INFO     
new value sent:
2019-04-20 10:14:19,271 INFO     realtime
-2.991 2.403 -0.458
2019-04-20 10:14:20,574 INFO     
entered while loop in thread
2019-04-20 10:14:20,577 INFO     
new value sent:
2019-04-20 10:14:20,578 INFO     realtime
-2.968 2.411 -0.542
2019-04-20 10:14:21,881 INFO     
entered while loop in thread
2019-04-20 10:14:21,885 INFO     
new value sent:
2019-04-20 10:14:21,886 INFO     realtime
-2.907 2.449 -0.481
2019-04-20 10:14:23,189 INFO     
entered while loop in thread
2019-04-20 10:14:23,208 INFO     
new value sent:
2019-04-20 10:14:23,209 INFO     realtime
-3.09 2.342 -0.496
2019-04-20 10:14:24,104 INFO     Received noMonitor
2019-04-20 10:14:24,107 INFO     put quit into que.
2019-04-20 10:14:24,109 INFO     quitting
2019-04-20 10:14:44,801 INFO     Received 1stop
2019-04-20 10:14:45,300 INFO     Received stop
2019-04-20 10:14:45,301 INFO     Motors stopping...
2019-04-20 10:14:45,517 INFO     Received 1stop
2019-04-20 10:14:51,301 INFO     Received stop
2019-04-20 10:14:51,302 INFO     Motors stopping...
2019-04-20 10:14:55,349 INFO     Received 1
2019-04-20 10:14:55,350 INFO     motors running forward
2019-04-20 10:14:55,581 INFO     Received stop
2019-04-20 10:14:55,582 INFO     Motors stopping...
2019-04-20 10:14:59,402 INFO     Received stop
2019-04-20 10:14:59,403 INFO     Motors stopping...
2019-04-20 10:15:03,936 INFO     Received 1
2019-04-20 10:15:03,937 INFO     motors running forward
2019-04-20 10:15:04,169 INFO     Received stop
2019-04-20 10:15:04,170 INFO     Motors stopping...
2019-04-20 10:15:08,665 INFO     Received stop
2019-04-20 10:15:08,666 INFO     Motors stopping...
2019-04-20 10:16:22,300 INFO     Received 2stop
2019-04-20 10:16:22,302 INFO     Received stop
2019-04-20 10:16:22,303 INFO     Motors stopping...
2019-04-20 10:16:22,800 INFO     Received 4stop
2019-04-20 10:16:23,285 INFO     Received stop
2019-04-20 10:16:23,286 INFO     Motors stopping...
2019-04-20 10:16:23,855 INFO     Received 3
2019-04-20 10:16:23,856 INFO     Received stop
2019-04-20 10:16:23,857 INFO     Motors stopping...
2019-04-20 10:16:24,296 INFO     Received stop
2019-04-20 10:16:24,297 INFO     Motors stopping...
2019-04-20 10:16:26,715 INFO     Received 3
2019-04-20 10:16:26,716 INFO     Received stop
2019-04-20 10:16:26,717 INFO     Motors stopping...
2019-04-20 10:16:27,847 INFO     Received stop
2019-04-20 10:16:27,857 INFO     Motors stopping...
2019-04-20 10:20:55,301 INFO     Received 1stop
2019-04-20 10:20:58,404 INFO     Received stop
2019-04-20 10:20:58,405 INFO     Motors stopping...
2019-04-20 10:21:00,725 INFO     Received 1stop
2019-04-20 10:21:02,785 INFO     Received stop
2019-04-20 10:21:02,786 INFO     Motors stopping...
2019-04-20 10:21:04,209 INFO     Received 1
2019-04-20 10:21:04,210 INFO     motors running forward
2019-04-20 10:21:04,441 INFO     Received stop
2019-04-20 10:21:04,442 INFO     Motors stopping...
2019-04-20 10:21:05,704 INFO     Received stop
2019-04-20 10:21:05,705 INFO     Motors stopping...
2019-04-20 10:21:07,495 INFO     Received 1stop
2019-04-20 10:21:10,284 INFO     Received stop
2019-04-20 10:21:10,285 INFO     Motors stopping...
2019-04-20 10:21:36,300 INFO     Received 1stop
2019-04-20 10:21:36,302 INFO     Received stop
2019-04-20 10:21:36,303 INFO     Motors stopping...
2019-04-20 10:21:36,800 INFO     Received 1
2019-04-20 10:21:36,801 INFO     motors running forward
2019-04-20 10:21:37,032 INFO     Received stopstop1stopstop1stopstop1stopstop
2019-04-20 10:32:21,299 ERROR    Unhandled exception in thread started by
2019-04-20 10:32:21,300 ERROR    <function threaded_bt at 0x70a11300>
2019-04-20 10:32:21,301 ERROR    Traceback (most recent call last):
2019-04-20 10:32:21,301 ERROR      File "<string>", line 3, in recv
2019-04-20 10:32:21,303 ERROR    _bluetooth
2019-04-20 10:32:21,303 ERROR    .
2019-04-20 10:32:21,304 ERROR    error
2019-04-20 10:32:21,305 ERROR    :
2019-04-20 10:32:21,305 ERROR    (104, 'Connection reset by peer')
2019-04-20 10:32:21,306 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 10:32:21,306 ERROR    Traceback (most recent call last):
2019-04-20 10:32:21,307 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 10:32:21,310 ERROR    data = conn.recv(1024)
2019-04-20 10:32:21,311 ERROR      File "<string>", line 5, in recv
2019-04-20 10:32:21,312 ERROR    bluetooth.btcommon
2019-04-20 10:32:21,313 ERROR    .
2019-04-20 10:32:21,314 ERROR    BluetoothError
2019-04-20 10:32:21,315 ERROR    :
2019-04-20 10:32:21,315 ERROR    (104, 'Connection reset by peer')
2019-04-20 10:32:33,487 INFO     client_sock
2019-04-20 10:32:33,489 INFO     <bluetooth.bluez.BluetoothSocket object at 0x70a2fd10>
2019-04-20 10:32:33,489 INFO     client_info
2019-04-20 10:32:33,490 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 10:32:33,491 INFO     slept enough
2019-04-20 10:32:33,493 INFO     Waiting for RFCOMM connection!!!
2019-04-20 10:32:33,811 INFO     Entered threaded client
2019-04-20 10:32:42,866 INFO     Received 1
2019-04-20 10:32:42,867 INFO     motors running forward
2019-04-20 10:32:44,321 INFO     Received stop
2019-04-20 10:32:44,322 INFO     Motors stopping...
2019-04-20 10:32:45,587 INFO     Received 1
2019-04-20 10:32:45,588 INFO     motors running forward
2019-04-20 10:32:46,162 INFO     Received stop
2019-04-20 10:32:46,163 INFO     Motors stopping...
2019-04-20 10:36:28,300 INFO     Received 1
2019-04-20 10:36:28,301 INFO     motors running forward
2019-04-20 10:36:28,532 INFO     Received stop
2019-04-20 10:36:28,533 INFO     Motors stopping...
2019-04-20 10:36:28,965 INFO     Received 1
2019-04-20 10:36:28,966 INFO     motors running forward
2019-04-20 10:36:29,867 INFO     Received stop
2019-04-20 10:36:29,869 INFO     Motors stopping...
2019-04-20 10:38:49,800 INFO     Received 1
2019-04-20 10:38:49,801 INFO     motors running forward
2019-04-20 10:38:50,298 INFO     Received stop
2019-04-20 10:38:50,299 INFO     Motors stopping...
2019-04-20 10:38:50,888 INFO     Received 1
2019-04-20 10:38:50,889 INFO     motors running forward
2019-04-20 10:38:51,506 INFO     Received stop
2019-04-20 10:38:51,507 INFO     Motors stopping...
2019-04-20 10:39:05,800 INFO     Received 2
2019-04-20 10:39:05,802 INFO     Received stop
2019-04-20 10:39:05,803 INFO     Motors stopping...
2019-04-20 10:39:06,298 INFO     Received 2
2019-04-20 10:39:06,302 INFO     Received stop
2019-04-20 10:39:06,303 INFO     Motors stopping...
2019-04-20 10:39:07,902 INFO     Received 4
2019-04-20 10:39:08,267 INFO     Received stop
2019-04-20 10:39:08,268 INFO     Motors stopping...
2019-04-20 10:39:08,797 INFO     Received 3
2019-04-20 10:39:09,260 INFO     Received stop
2019-04-20 10:39:09,261 INFO     Motors stopping...
2019-04-20 10:39:10,173 INFO     Received 1
2019-04-20 10:39:10,175 INFO     motors running forward
2019-04-20 10:39:10,636 INFO     Received stop
2019-04-20 10:39:10,637 INFO     Motors stopping...
2019-04-20 10:39:10,935 INFO     Received 1
2019-04-20 10:39:10,944 INFO     motors running forward
2019-04-20 10:39:11,176 INFO     Received stop
2019-04-20 10:39:11,177 INFO     Motors stopping...
2019-04-20 10:39:11,331 INFO     Received 1
2019-04-20 10:39:11,332 INFO     motors running forward
2019-04-20 10:39:11,563 INFO     Received stop
2019-04-20 10:39:11,564 INFO     Motors stopping...
2019-04-20 10:39:11,681 INFO     Received 1
2019-04-20 10:39:11,682 INFO     motors running forward
2019-04-20 10:39:11,913 INFO     Received stop1stop
2019-04-20 10:39:11,970 INFO     Received 1
2019-04-20 10:39:11,971 INFO     motors running forward
2019-04-20 10:39:12,202 INFO     Received stop
2019-04-20 10:39:12,203 INFO     Motors stopping...
2019-04-20 10:39:12,620 INFO     Received 1
2019-04-20 10:39:12,621 INFO     motors running forward
2019-04-20 10:39:12,886 INFO     Received stop
2019-04-20 10:39:12,887 INFO     Motors stopping...
2019-04-20 10:39:13,153 INFO     Received 1
2019-04-20 10:39:13,154 INFO     motors running forward
2019-04-20 10:39:13,416 INFO     Received stop
2019-04-20 10:39:13,417 INFO     Motors stopping...
2019-04-20 10:39:13,803 INFO     Received 1
2019-04-20 10:39:13,804 INFO     motors running forward
2019-04-20 10:39:14,678 INFO     Received stop
2019-04-20 10:39:14,680 INFO     Motors stopping...
2019-04-20 10:39:15,152 INFO     Received 1
2019-04-20 10:39:15,153 INFO     motors running forward
2019-04-20 10:39:15,968 INFO     Received stop
2019-04-20 10:39:15,970 INFO     Motors stopping...
2019-04-20 10:39:16,331 INFO     Received 1
2019-04-20 10:39:16,332 INFO     motors running forward
2019-04-20 10:39:17,122 INFO     Received stop
2019-04-20 10:39:17,123 INFO     Motors stopping...
2019-04-20 10:39:17,413 INFO     Received 1
2019-04-20 10:39:17,414 INFO     motors running forward
2019-04-20 10:39:18,093 INFO     Received stop
2019-04-20 10:39:18,094 INFO     Motors stopping...
2019-04-20 10:39:18,437 INFO     Received 1
2019-04-20 10:39:18,438 INFO     motors running forward
2019-04-20 10:39:18,956 INFO     Received stop
2019-04-20 10:39:18,957 INFO     Motors stopping...
2019-04-20 10:39:19,240 INFO     Received 1
2019-04-20 10:39:19,241 INFO     motors running forward
2019-04-20 10:39:19,797 INFO     Received stop
2019-04-20 10:39:19,798 INFO     Motors stopping...
2019-04-20 10:39:20,076 INFO     Received 1
2019-04-20 10:39:20,077 INFO     motors running forward
2019-04-20 10:39:21,983 INFO     Received stop
2019-04-20 10:39:21,985 INFO     Motors stopping...
2019-04-20 13:07:17,145 INFO     setup_logging done
2019-04-20 13:07:27,430 INFO     slept enough
2019-04-20 13:07:27,431 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:07:41,652 INFO     client_sock
2019-04-20 13:07:41,653 INFO     <bluetooth.bluez.BluetoothSocket object at 0x70971cf0>
2019-04-20 13:07:41,654 INFO     client_info
2019-04-20 13:07:41,655 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:07:41,656 INFO     slept enough
2019-04-20 13:07:41,658 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:07:41,977 INFO     Entered threaded client
2019-04-20 13:08:38,929 INFO     Received 1
2019-04-20 13:08:38,931 INFO     motors running forward
2019-04-20 13:08:39,932 INFO     motors running forward
2019-04-20 13:08:41,011 INFO     motors running forward
2019-04-20 13:08:42,167 INFO     Received stop
2019-04-20 13:08:42,168 INFO     motors running forward
2019-04-20 13:08:43,401 INFO     motors running forward
2019-04-20 13:08:44,557 INFO     motors running forward
2019-04-20 13:08:45,653 INFO     Motors stopping...
2019-04-20 13:09:52,961 ERROR    Traceback (most recent call last):
2019-04-20 13:09:52,962 ERROR      File "uus.py", line 273, in <module>
2019-04-20 13:09:52,964 ERROR      File "uus.py", line 182, in main
2019-04-20 13:09:52,967 ERROR    accept_connection(server_sock)
2019-04-20 13:09:52,967 ERROR      File "uus.py", line 265, in accept_connection
2019-04-20 13:09:52,970 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 167, in accept
2019-04-20 13:09:52,976 ERROR    client, addr = self._sock.accept ()
2019-04-20 13:09:52,976 ERROR    KeyboardInterrupt
2019-04-20 13:09:52,978 ERROR    Exception ignored in:
2019-04-20 13:09:52,980 ERROR    <__main__.LoggerHelper object at 0x70971f30>
2019-04-20 13:09:52,980 ERROR    AttributeError
2019-04-20 13:09:52,981 ERROR    :
2019-04-20 13:09:52,982 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-20 13:09:54,358 INFO     setup_logging done
2019-04-20 13:10:04,439 INFO     slept enough
2019-04-20 13:10:04,440 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:11:26,955 INFO     client_sock
2019-04-20 13:11:26,956 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:11:26,957 INFO     client_info
2019-04-20 13:11:26,958 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:11:26,959 INFO     slept enough
2019-04-20 13:11:26,961 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:11:27,280 INFO     Entered threaded client
2019-04-20 13:13:49,669 ERROR    Unhandled exception in thread started by
2019-04-20 13:13:49,670 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:13:49,671 ERROR    Traceback (most recent call last):
2019-04-20 13:13:49,672 ERROR      File "<string>", line 3, in recv
2019-04-20 13:13:49,673 ERROR    _bluetooth
2019-04-20 13:13:49,674 ERROR    .
2019-04-20 13:13:49,675 ERROR    error
2019-04-20 13:13:49,676 ERROR    :
2019-04-20 13:13:49,677 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:13:49,677 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:13:49,678 ERROR    Traceback (most recent call last):
2019-04-20 13:13:49,679 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:13:49,681 ERROR    data = conn.recv(1024)
2019-04-20 13:13:49,682 ERROR      File "<string>", line 5, in recv
2019-04-20 13:13:49,683 ERROR    bluetooth.btcommon
2019-04-20 13:13:49,684 ERROR    .
2019-04-20 13:13:49,685 ERROR    BluetoothError
2019-04-20 13:13:49,685 ERROR    :
2019-04-20 13:13:49,686 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:14:00,636 INFO     client_sock
2019-04-20 13:14:00,637 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:14:00,638 INFO     client_info
2019-04-20 13:14:00,638 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:14:00,639 INFO     slept enough
2019-04-20 13:14:00,641 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:14:00,960 INFO     Entered threaded client
2019-04-20 13:15:10,046 ERROR    Unhandled exception in thread started by
2019-04-20 13:15:10,047 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:15:10,048 ERROR    Traceback (most recent call last):
2019-04-20 13:15:10,049 ERROR      File "<string>", line 3, in recv
2019-04-20 13:15:10,051 ERROR    _bluetooth
2019-04-20 13:15:10,051 ERROR    .
2019-04-20 13:15:10,052 ERROR    error
2019-04-20 13:15:10,053 ERROR    :
2019-04-20 13:15:10,054 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:15:10,055 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:15:10,056 ERROR    Traceback (most recent call last):
2019-04-20 13:15:10,057 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:15:10,059 ERROR    data = conn.recv(1024)
2019-04-20 13:15:10,060 ERROR      File "<string>", line 5, in recv
2019-04-20 13:15:10,061 ERROR    bluetooth.btcommon
2019-04-20 13:15:10,062 ERROR    .
2019-04-20 13:15:10,063 ERROR    BluetoothError
2019-04-20 13:15:10,063 ERROR    :
2019-04-20 13:15:10,064 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:15:19,915 INFO     client_sock
2019-04-20 13:15:19,916 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:15:19,917 INFO     client_info
2019-04-20 13:15:19,917 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:15:19,918 INFO     slept enough
2019-04-20 13:15:19,919 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:15:20,238 INFO     Entered threaded client
2019-04-20 13:15:20,239 ERROR    Unhandled exception in thread started by
2019-04-20 13:15:20,240 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:15:20,240 ERROR    Traceback (most recent call last):
2019-04-20 13:15:20,241 ERROR      File "<string>", line 3, in recv
2019-04-20 13:15:20,243 ERROR    _bluetooth
2019-04-20 13:15:20,243 ERROR    .
2019-04-20 13:15:20,244 ERROR    error
2019-04-20 13:15:20,245 ERROR    :
2019-04-20 13:15:20,246 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:15:20,246 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:15:20,247 ERROR    Traceback (most recent call last):
2019-04-20 13:15:20,248 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:15:20,250 ERROR    data = conn.recv(1024)
2019-04-20 13:15:20,250 ERROR      File "<string>", line 5, in recv
2019-04-20 13:15:20,252 ERROR    bluetooth.btcommon
2019-04-20 13:15:20,252 ERROR    .
2019-04-20 13:15:20,253 ERROR    BluetoothError
2019-04-20 13:15:20,254 ERROR    :
2019-04-20 13:15:20,254 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:16:40,565 INFO     client_sock
2019-04-20 13:16:40,566 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:16:40,566 INFO     client_info
2019-04-20 13:16:40,567 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:16:40,568 INFO     slept enough
2019-04-20 13:16:40,569 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:16:40,888 INFO     Entered threaded client
2019-04-20 13:16:40,889 ERROR    Unhandled exception in thread started by
2019-04-20 13:16:40,890 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:16:40,890 ERROR    Traceback (most recent call last):
2019-04-20 13:16:40,891 ERROR      File "<string>", line 3, in recv
2019-04-20 13:16:40,892 ERROR    _bluetooth
2019-04-20 13:16:40,893 ERROR    .
2019-04-20 13:16:40,894 ERROR    error
2019-04-20 13:16:40,895 ERROR    :
2019-04-20 13:16:40,895 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:16:40,896 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:16:40,897 ERROR    Traceback (most recent call last):
2019-04-20 13:16:40,898 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:16:40,900 ERROR    data = conn.recv(1024)
2019-04-20 13:16:40,901 ERROR      File "<string>", line 5, in recv
2019-04-20 13:16:40,902 ERROR    bluetooth.btcommon
2019-04-20 13:16:40,903 ERROR    .
2019-04-20 13:16:40,904 ERROR    BluetoothError
2019-04-20 13:16:40,904 ERROR    :
2019-04-20 13:16:40,905 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:20:57,846 INFO     client_sock
2019-04-20 13:20:57,847 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:20:57,847 INFO     client_info
2019-04-20 13:20:57,848 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:20:57,849 INFO     slept enough
2019-04-20 13:20:57,850 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:20:58,169 INFO     Entered threaded client
2019-04-20 13:24:59,671 ERROR    Unhandled exception in thread started by
2019-04-20 13:24:59,672 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:24:59,672 ERROR    Traceback (most recent call last):
2019-04-20 13:24:59,673 ERROR      File "<string>", line 3, in recv
2019-04-20 13:24:59,674 ERROR    _bluetooth
2019-04-20 13:24:59,675 ERROR    .
2019-04-20 13:24:59,676 ERROR    error
2019-04-20 13:24:59,677 ERROR    :
2019-04-20 13:24:59,677 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:24:59,678 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:24:59,679 ERROR    Traceback (most recent call last):
2019-04-20 13:24:59,680 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:24:59,682 ERROR    data = conn.recv(1024)
2019-04-20 13:24:59,683 ERROR      File "<string>", line 5, in recv
2019-04-20 13:24:59,684 ERROR    bluetooth.btcommon
2019-04-20 13:24:59,685 ERROR    .
2019-04-20 13:24:59,686 ERROR    BluetoothError
2019-04-20 13:24:59,687 ERROR    :
2019-04-20 13:24:59,688 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:25:52,239 INFO     client_sock
2019-04-20 13:25:52,240 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:25:52,241 INFO     client_info
2019-04-20 13:25:52,242 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:25:52,243 INFO     slept enough
2019-04-20 13:25:52,244 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:25:52,563 INFO     Entered threaded client
2019-04-20 13:34:53,490 ERROR    Unhandled exception in thread started by
2019-04-20 13:34:53,491 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:34:53,492 ERROR    Traceback (most recent call last):
2019-04-20 13:34:53,493 ERROR      File "<string>", line 3, in recv
2019-04-20 13:34:53,494 ERROR    _bluetooth
2019-04-20 13:34:53,495 ERROR    .
2019-04-20 13:34:53,496 ERROR    error
2019-04-20 13:34:53,497 ERROR    :
2019-04-20 13:34:53,497 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:34:53,498 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:34:53,499 ERROR    Traceback (most recent call last):
2019-04-20 13:34:53,499 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:34:53,501 ERROR    data = conn.recv(1024)
2019-04-20 13:34:53,502 ERROR      File "<string>", line 5, in recv
2019-04-20 13:34:53,504 ERROR    bluetooth.btcommon
2019-04-20 13:34:53,504 ERROR    .
2019-04-20 13:34:53,505 ERROR    BluetoothError
2019-04-20 13:34:53,506 ERROR    :
2019-04-20 13:34:53,507 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:35:05,209 INFO     client_sock
2019-04-20 13:35:05,210 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:35:05,211 INFO     client_info
2019-04-20 13:35:05,211 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:35:05,212 INFO     slept enough
2019-04-20 13:35:05,213 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:35:05,532 INFO     Entered threaded client
2019-04-20 13:35:05,533 ERROR    Unhandled exception in thread started by
2019-04-20 13:35:05,534 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:35:05,535 ERROR    Traceback (most recent call last):
2019-04-20 13:35:05,535 ERROR      File "<string>", line 3, in recv
2019-04-20 13:35:05,537 ERROR    _bluetooth
2019-04-20 13:35:05,538 ERROR    .
2019-04-20 13:35:05,538 ERROR    error
2019-04-20 13:35:05,539 ERROR    :
2019-04-20 13:35:05,539 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:35:05,540 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:35:05,541 ERROR    Traceback (most recent call last):
2019-04-20 13:35:05,541 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:35:05,543 ERROR    data = conn.recv(1024)
2019-04-20 13:35:05,544 ERROR      File "<string>", line 5, in recv
2019-04-20 13:35:05,545 ERROR    bluetooth.btcommon
2019-04-20 13:35:05,546 ERROR    .
2019-04-20 13:35:05,547 ERROR    BluetoothError
2019-04-20 13:35:05,547 ERROR    :
2019-04-20 13:35:05,548 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:39:59,698 INFO     client_sock
2019-04-20 13:39:59,699 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:39:59,699 INFO     client_info
2019-04-20 13:39:59,700 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:39:59,701 INFO     slept enough
2019-04-20 13:39:59,702 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:40:00,021 INFO     Entered threaded client
2019-04-20 13:40:00,022 ERROR    Unhandled exception in thread started by
2019-04-20 13:40:00,024 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:40:00,025 ERROR    Traceback (most recent call last):
2019-04-20 13:40:00,026 ERROR      File "<string>", line 3, in recv
2019-04-20 13:40:00,027 ERROR    _bluetooth
2019-04-20 13:40:00,028 ERROR    .
2019-04-20 13:40:00,029 ERROR    error
2019-04-20 13:40:00,030 ERROR    :
2019-04-20 13:40:00,031 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:40:00,032 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:40:00,033 ERROR    Traceback (most recent call last):
2019-04-20 13:40:00,034 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:40:00,036 ERROR    data = conn.recv(1024)
2019-04-20 13:40:00,037 ERROR      File "<string>", line 5, in recv
2019-04-20 13:40:00,039 ERROR    bluetooth.btcommon
2019-04-20 13:40:00,040 ERROR    .
2019-04-20 13:40:00,041 ERROR    BluetoothError
2019-04-20 13:40:00,042 ERROR    :
2019-04-20 13:40:00,043 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:40:27,759 INFO     client_sock
2019-04-20 13:40:27,760 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:40:27,761 INFO     client_info
2019-04-20 13:40:27,762 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:40:27,763 INFO     slept enough
2019-04-20 13:40:27,764 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:40:28,083 INFO     Entered threaded client
2019-04-20 13:41:19,760 ERROR    Unhandled exception in thread started by
2019-04-20 13:41:19,761 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:41:19,762 ERROR    Traceback (most recent call last):
2019-04-20 13:41:19,762 ERROR      File "<string>", line 3, in recv
2019-04-20 13:41:19,764 ERROR    _bluetooth
2019-04-20 13:41:19,765 ERROR    .
2019-04-20 13:41:19,766 ERROR    error
2019-04-20 13:41:19,766 ERROR    :
2019-04-20 13:41:19,767 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:41:19,768 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:41:19,769 ERROR    Traceback (most recent call last):
2019-04-20 13:41:19,769 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:41:19,772 ERROR    data = conn.recv(1024)
2019-04-20 13:41:19,772 ERROR      File "<string>", line 5, in recv
2019-04-20 13:41:19,774 ERROR    bluetooth.btcommon
2019-04-20 13:41:19,775 ERROR    .
2019-04-20 13:41:19,775 ERROR    BluetoothError
2019-04-20 13:41:19,776 ERROR    :
2019-04-20 13:41:19,777 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:41:34,351 INFO     client_sock
2019-04-20 13:41:34,352 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:41:34,353 INFO     client_info
2019-04-20 13:41:34,354 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:41:34,355 INFO     slept enough
2019-04-20 13:41:34,356 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:41:34,675 INFO     Entered threaded client
2019-04-20 13:42:15,465 ERROR    Unhandled exception in thread started by
2019-04-20 13:42:15,466 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:42:15,467 ERROR    Traceback (most recent call last):
2019-04-20 13:42:15,468 ERROR      File "<string>", line 3, in recv
2019-04-20 13:42:15,469 ERROR    _bluetooth
2019-04-20 13:42:15,470 ERROR    .
2019-04-20 13:42:15,471 ERROR    error
2019-04-20 13:42:15,472 ERROR    :
2019-04-20 13:42:15,472 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:42:15,473 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:42:15,474 ERROR    Traceback (most recent call last):
2019-04-20 13:42:15,475 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:42:15,477 ERROR    data = conn.recv(1024)
2019-04-20 13:42:15,478 ERROR      File "<string>", line 5, in recv
2019-04-20 13:42:15,480 ERROR    bluetooth.btcommon
2019-04-20 13:42:15,481 ERROR    .
2019-04-20 13:42:15,481 ERROR    BluetoothError
2019-04-20 13:42:15,482 ERROR    :
2019-04-20 13:42:15,483 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:42:28,119 INFO     client_sock
2019-04-20 13:42:28,121 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:42:28,121 INFO     client_info
2019-04-20 13:42:28,122 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:42:28,122 INFO     slept enough
2019-04-20 13:42:28,123 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:42:28,443 INFO     Entered threaded client
2019-04-20 13:47:55,996 ERROR    Unhandled exception in thread started by
2019-04-20 13:47:55,997 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 13:47:55,998 ERROR    Traceback (most recent call last):
2019-04-20 13:47:55,998 ERROR      File "<string>", line 3, in recv
2019-04-20 13:47:55,999 ERROR    _bluetooth
2019-04-20 13:47:56,000 ERROR    .
2019-04-20 13:47:56,001 ERROR    error
2019-04-20 13:47:56,001 ERROR    :
2019-04-20 13:47:56,002 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:47:56,002 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 13:47:56,003 ERROR    Traceback (most recent call last):
2019-04-20 13:47:56,003 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 13:47:56,006 ERROR    data = conn.recv(1024)
2019-04-20 13:47:56,007 ERROR      File "<string>", line 5, in recv
2019-04-20 13:47:56,009 ERROR    bluetooth.btcommon
2019-04-20 13:47:56,010 ERROR    .
2019-04-20 13:47:56,011 ERROR    BluetoothError
2019-04-20 13:47:56,011 ERROR    :
2019-04-20 13:47:56,012 ERROR    (104, 'Connection reset by peer')
2019-04-20 13:56:04,677 INFO     client_sock
2019-04-20 13:56:04,678 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 13:56:04,679 INFO     client_info
2019-04-20 13:56:04,680 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 13:56:04,680 INFO     slept enough
2019-04-20 13:56:04,682 INFO     Waiting for RFCOMM connection!!!
2019-04-20 13:56:05,000 INFO     Entered threaded client
2019-04-20 14:01:08,567 ERROR    Unhandled exception in thread started by
2019-04-20 14:01:08,568 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 14:01:08,569 ERROR    Traceback (most recent call last):
2019-04-20 14:01:08,570 ERROR      File "<string>", line 3, in recv
2019-04-20 14:01:08,571 ERROR    _bluetooth
2019-04-20 14:01:08,572 ERROR    .
2019-04-20 14:01:08,573 ERROR    error
2019-04-20 14:01:08,574 ERROR    :
2019-04-20 14:01:08,575 ERROR    (104, 'Connection reset by peer')
2019-04-20 14:01:08,576 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 14:01:08,576 ERROR    Traceback (most recent call last):
2019-04-20 14:01:08,577 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 14:01:08,580 ERROR    data = conn.recv(1024)
2019-04-20 14:01:08,580 ERROR      File "<string>", line 5, in recv
2019-04-20 14:01:08,582 ERROR    bluetooth.btcommon
2019-04-20 14:01:08,583 ERROR    .
2019-04-20 14:01:08,583 ERROR    BluetoothError
2019-04-20 14:01:08,584 ERROR    :
2019-04-20 14:01:08,585 ERROR    (104, 'Connection reset by peer')
2019-04-20 14:01:50,276 INFO     client_sock
2019-04-20 14:01:50,277 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 14:01:50,277 INFO     client_info
2019-04-20 14:01:50,278 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 14:01:50,279 INFO     slept enough
2019-04-20 14:01:50,281 INFO     Waiting for RFCOMM connection!!!
2019-04-20 14:01:50,599 INFO     Entered threaded client
2019-04-20 14:08:46,072 ERROR    Unhandled exception in thread started by
2019-04-20 14:08:46,073 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 14:08:46,074 ERROR    Traceback (most recent call last):
2019-04-20 14:08:46,074 ERROR      File "<string>", line 3, in recv
2019-04-20 14:08:46,076 ERROR    _bluetooth
2019-04-20 14:08:46,077 ERROR    .
2019-04-20 14:08:46,077 ERROR    error
2019-04-20 14:08:46,078 ERROR    :
2019-04-20 14:08:46,079 ERROR    (104, 'Connection reset by peer')
2019-04-20 14:08:46,079 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 14:08:46,080 ERROR    Traceback (most recent call last):
2019-04-20 14:08:46,081 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 14:08:46,083 ERROR    data = conn.recv(1024)
2019-04-20 14:08:46,084 ERROR      File "<string>", line 5, in recv
2019-04-20 14:08:46,085 ERROR    bluetooth.btcommon
2019-04-20 14:08:46,086 ERROR    .
2019-04-20 14:08:46,086 ERROR    BluetoothError
2019-04-20 14:08:46,087 ERROR    :
2019-04-20 14:08:46,088 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:20:32,846 INFO     client_sock
2019-04-20 16:20:32,847 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:20:32,848 INFO     client_info
2019-04-20 16:20:32,849 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:20:32,850 INFO     slept enough
2019-04-20 16:20:32,851 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:20:33,170 INFO     Entered threaded client
2019-04-20 16:20:33,171 ERROR    Unhandled exception in thread started by
2019-04-20 16:20:33,171 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:20:33,172 ERROR    Traceback (most recent call last):
2019-04-20 16:20:33,173 ERROR      File "<string>", line 3, in recv
2019-04-20 16:20:33,174 ERROR    _bluetooth
2019-04-20 16:20:33,175 ERROR    .
2019-04-20 16:20:33,176 ERROR    error
2019-04-20 16:20:33,176 ERROR    :
2019-04-20 16:20:33,177 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:20:33,178 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:20:33,178 ERROR    Traceback (most recent call last):
2019-04-20 16:20:33,179 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:20:33,181 ERROR    data = conn.recv(1024)
2019-04-20 16:20:33,182 ERROR      File "<string>", line 5, in recv
2019-04-20 16:20:33,183 ERROR    bluetooth.btcommon
2019-04-20 16:20:33,184 ERROR    .
2019-04-20 16:20:33,184 ERROR    BluetoothError
2019-04-20 16:20:33,185 ERROR    :
2019-04-20 16:20:33,186 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:24:43,790 INFO     client_sock
2019-04-20 16:24:43,791 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:24:43,792 INFO     client_info
2019-04-20 16:24:43,792 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:24:43,793 INFO     slept enough
2019-04-20 16:24:43,794 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:24:44,114 INFO     Entered threaded client
2019-04-20 16:24:44,115 ERROR    Unhandled exception in thread started by
2019-04-20 16:24:44,116 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:24:44,117 ERROR    Traceback (most recent call last):
2019-04-20 16:24:44,117 ERROR      File "<string>", line 3, in recv
2019-04-20 16:24:44,119 ERROR    _bluetooth
2019-04-20 16:24:44,120 ERROR    .
2019-04-20 16:24:44,121 ERROR    error
2019-04-20 16:24:44,121 ERROR    :
2019-04-20 16:24:44,122 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:24:44,123 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:24:44,123 ERROR    Traceback (most recent call last):
2019-04-20 16:24:44,124 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:24:44,126 ERROR    data = conn.recv(1024)
2019-04-20 16:24:44,127 ERROR      File "<string>", line 5, in recv
2019-04-20 16:24:44,128 ERROR    bluetooth.btcommon
2019-04-20 16:24:44,129 ERROR    .
2019-04-20 16:24:44,130 ERROR    BluetoothError
2019-04-20 16:24:44,130 ERROR    :
2019-04-20 16:24:44,131 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:25:45,513 INFO     setup_logging done
2019-04-20 16:25:55,601 INFO     slept enough
2019-04-20 16:25:55,602 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:30:02,487 INFO     client_sock
2019-04-20 16:30:02,488 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:30:02,489 INFO     client_info
2019-04-20 16:30:02,489 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:30:02,490 INFO     slept enough
2019-04-20 16:30:02,492 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:30:02,810 INFO     Entered threaded client
2019-04-20 16:30:02,812 ERROR    Unhandled exception in thread started by
2019-04-20 16:30:02,812 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:30:02,813 ERROR    Traceback (most recent call last):
2019-04-20 16:30:02,814 ERROR      File "<string>", line 3, in recv
2019-04-20 16:30:02,816 ERROR    _bluetooth
2019-04-20 16:30:02,816 ERROR    .
2019-04-20 16:30:02,817 ERROR    error
2019-04-20 16:30:02,818 ERROR    :
2019-04-20 16:30:02,819 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:30:02,819 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:30:02,820 ERROR    Traceback (most recent call last):
2019-04-20 16:30:02,821 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:30:02,823 ERROR    data = conn.recv(1024)
2019-04-20 16:30:02,824 ERROR      File "<string>", line 5, in recv
2019-04-20 16:30:02,826 ERROR    bluetooth.btcommon
2019-04-20 16:30:02,826 ERROR    .
2019-04-20 16:30:02,827 ERROR    BluetoothError
2019-04-20 16:30:02,828 ERROR    :
2019-04-20 16:30:02,829 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:41:58,205 INFO     client_sock
2019-04-20 16:41:58,206 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:41:58,207 INFO     client_info
2019-04-20 16:41:58,207 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:41:58,208 INFO     slept enough
2019-04-20 16:41:58,209 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:41:58,528 INFO     Entered threaded client
2019-04-20 16:41:58,529 ERROR    Unhandled exception in thread started by
2019-04-20 16:41:58,529 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:41:58,530 ERROR    Traceback (most recent call last):
2019-04-20 16:41:58,531 ERROR      File "<string>", line 3, in recv
2019-04-20 16:41:58,532 ERROR    _bluetooth
2019-04-20 16:41:58,532 ERROR    .
2019-04-20 16:41:58,533 ERROR    error
2019-04-20 16:41:58,533 ERROR    :
2019-04-20 16:41:58,534 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:41:58,534 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:41:58,535 ERROR    Traceback (most recent call last):
2019-04-20 16:41:58,536 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:41:58,538 ERROR    data = conn.recv(1024)
2019-04-20 16:41:58,538 ERROR      File "<string>", line 5, in recv
2019-04-20 16:41:58,539 ERROR    bluetooth.btcommon
2019-04-20 16:41:58,540 ERROR    .
2019-04-20 16:41:58,541 ERROR    BluetoothError
2019-04-20 16:41:58,541 ERROR    :
2019-04-20 16:41:58,542 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:42:17,404 INFO     client_sock
2019-04-20 16:42:17,405 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:42:17,406 INFO     client_info
2019-04-20 16:42:17,406 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:42:17,407 INFO     slept enough
2019-04-20 16:42:17,408 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:42:17,727 INFO     Entered threaded client
2019-04-20 16:42:17,728 ERROR    Unhandled exception in thread started by
2019-04-20 16:42:17,728 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:42:17,729 ERROR    Traceback (most recent call last):
2019-04-20 16:42:17,729 ERROR      File "<string>", line 3, in recv
2019-04-20 16:42:17,731 ERROR    _bluetooth
2019-04-20 16:42:17,731 ERROR    .
2019-04-20 16:42:17,732 ERROR    error
2019-04-20 16:42:17,732 ERROR    :
2019-04-20 16:42:17,733 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:42:17,733 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:42:17,734 ERROR    Traceback (most recent call last):
2019-04-20 16:42:17,734 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:42:17,736 ERROR    data = conn.recv(1024)
2019-04-20 16:42:17,737 ERROR      File "<string>", line 5, in recv
2019-04-20 16:42:17,738 ERROR    bluetooth.btcommon
2019-04-20 16:42:17,739 ERROR    .
2019-04-20 16:42:17,739 ERROR    BluetoothError
2019-04-20 16:42:17,740 ERROR    :
2019-04-20 16:42:17,740 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:43:45,499 INFO     client_sock
2019-04-20 16:43:45,500 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:43:45,500 INFO     client_info
2019-04-20 16:43:45,501 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:43:45,502 INFO     slept enough
2019-04-20 16:43:45,502 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:43:45,822 INFO     Entered threaded client
2019-04-20 16:43:45,823 ERROR    Unhandled exception in thread started by
2019-04-20 16:43:45,824 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:43:45,824 ERROR    Traceback (most recent call last):
2019-04-20 16:43:45,825 ERROR      File "<string>", line 3, in recv
2019-04-20 16:43:45,826 ERROR    _bluetooth
2019-04-20 16:43:45,827 ERROR    .
2019-04-20 16:43:45,827 ERROR    error
2019-04-20 16:43:45,828 ERROR    :
2019-04-20 16:43:45,828 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:43:45,829 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:43:45,829 ERROR    Traceback (most recent call last):
2019-04-20 16:43:45,830 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:43:45,832 ERROR    data = conn.recv(1024)
2019-04-20 16:43:45,833 ERROR      File "<string>", line 5, in recv
2019-04-20 16:43:45,834 ERROR    bluetooth.btcommon
2019-04-20 16:43:45,834 ERROR    .
2019-04-20 16:43:45,835 ERROR    BluetoothError
2019-04-20 16:43:45,835 ERROR    :
2019-04-20 16:43:45,836 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:44:23,891 INFO     client_sock
2019-04-20 16:44:23,892 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:44:23,893 INFO     client_info
2019-04-20 16:44:23,893 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:44:23,894 INFO     slept enough
2019-04-20 16:44:23,895 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:44:24,215 INFO     Entered threaded client
2019-04-20 16:44:24,216 ERROR    Unhandled exception in thread started by
2019-04-20 16:44:24,216 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:44:24,217 ERROR    Traceback (most recent call last):
2019-04-20 16:44:24,217 ERROR      File "<string>", line 3, in recv
2019-04-20 16:44:24,219 ERROR    _bluetooth
2019-04-20 16:44:24,219 ERROR    .
2019-04-20 16:44:24,220 ERROR    error
2019-04-20 16:44:24,220 ERROR    :
2019-04-20 16:44:24,221 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:44:24,221 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:44:24,222 ERROR    Traceback (most recent call last):
2019-04-20 16:44:24,222 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:44:24,224 ERROR    data = conn.recv(1024)
2019-04-20 16:44:24,225 ERROR      File "<string>", line 5, in recv
2019-04-20 16:44:24,226 ERROR    bluetooth.btcommon
2019-04-20 16:44:24,227 ERROR    .
2019-04-20 16:44:24,227 ERROR    BluetoothError
2019-04-20 16:44:24,228 ERROR    :
2019-04-20 16:44:24,228 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:46:08,825 INFO     client_sock
2019-04-20 16:46:08,826 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:46:08,826 INFO     client_info
2019-04-20 16:46:08,827 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:46:08,828 INFO     slept enough
2019-04-20 16:46:08,828 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:46:09,148 INFO     Entered threaded client
2019-04-20 16:46:09,149 ERROR    Unhandled exception in thread started by
2019-04-20 16:46:09,150 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:46:09,150 ERROR    Traceback (most recent call last):
2019-04-20 16:46:09,151 ERROR      File "<string>", line 3, in recv
2019-04-20 16:46:09,152 ERROR    _bluetooth
2019-04-20 16:46:09,153 ERROR    .
2019-04-20 16:46:09,153 ERROR    error
2019-04-20 16:46:09,154 ERROR    :
2019-04-20 16:46:09,154 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:46:09,155 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:46:09,156 ERROR    Traceback (most recent call last):
2019-04-20 16:46:09,156 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:46:09,158 ERROR    data = conn.recv(1024)
2019-04-20 16:46:09,159 ERROR      File "<string>", line 5, in recv
2019-04-20 16:46:09,160 ERROR    bluetooth.btcommon
2019-04-20 16:46:09,160 ERROR    .
2019-04-20 16:46:09,161 ERROR    BluetoothError
2019-04-20 16:46:09,162 ERROR    :
2019-04-20 16:46:09,162 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:50:17,175 INFO     client_sock
2019-04-20 16:50:17,176 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:50:17,176 INFO     client_info
2019-04-20 16:50:17,177 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:50:17,178 INFO     slept enough
2019-04-20 16:50:17,179 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:50:17,497 INFO     Entered threaded client
2019-04-20 16:50:17,498 ERROR    Unhandled exception in thread started by
2019-04-20 16:50:17,499 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:50:17,499 ERROR    Traceback (most recent call last):
2019-04-20 16:50:17,500 ERROR      File "<string>", line 3, in recv
2019-04-20 16:50:17,501 ERROR    _bluetooth
2019-04-20 16:50:17,502 ERROR    .
2019-04-20 16:50:17,502 ERROR    error
2019-04-20 16:50:17,503 ERROR    :
2019-04-20 16:50:17,503 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:50:17,504 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:50:17,504 ERROR    Traceback (most recent call last):
2019-04-20 16:50:17,505 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:50:17,507 ERROR    data = conn.recv(1024)
2019-04-20 16:50:17,508 ERROR      File "<string>", line 5, in recv
2019-04-20 16:50:17,509 ERROR    bluetooth.btcommon
2019-04-20 16:50:17,509 ERROR    .
2019-04-20 16:50:17,510 ERROR    BluetoothError
2019-04-20 16:50:17,511 ERROR    :
2019-04-20 16:50:17,511 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:50:41,490 INFO     client_sock
2019-04-20 16:50:41,491 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 16:50:41,491 INFO     client_info
2019-04-20 16:50:41,492 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 16:50:41,492 INFO     slept enough
2019-04-20 16:50:41,494 INFO     Waiting for RFCOMM connection!!!
2019-04-20 16:50:41,812 INFO     Entered threaded client
2019-04-20 16:50:41,813 ERROR    Unhandled exception in thread started by
2019-04-20 16:50:41,814 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 16:50:41,815 ERROR    Traceback (most recent call last):
2019-04-20 16:50:41,815 ERROR      File "<string>", line 3, in recv
2019-04-20 16:50:41,817 ERROR    _bluetooth
2019-04-20 16:50:41,817 ERROR    .
2019-04-20 16:50:41,818 ERROR    error
2019-04-20 16:50:41,818 ERROR    :
2019-04-20 16:50:41,819 ERROR    (104, 'Connection reset by peer')
2019-04-20 16:50:41,819 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 16:50:41,820 ERROR    Traceback (most recent call last):
2019-04-20 16:50:41,821 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 16:50:41,823 ERROR    data = conn.recv(1024)
2019-04-20 16:50:41,823 ERROR      File "<string>", line 5, in recv
2019-04-20 16:50:41,824 ERROR    bluetooth.btcommon
2019-04-20 16:50:41,825 ERROR    .
2019-04-20 16:50:41,826 ERROR    BluetoothError
2019-04-20 16:50:41,826 ERROR    :
2019-04-20 16:50:41,827 ERROR    (104, 'Connection reset by peer')
2019-04-20 17:04:14,278 INFO     client_sock
2019-04-20 17:04:14,279 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 17:04:14,279 INFO     client_info
2019-04-20 17:04:14,280 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 17:04:14,281 INFO     slept enough
2019-04-20 17:04:14,282 INFO     Waiting for RFCOMM connection!!!
2019-04-20 17:04:14,601 INFO     Entered threaded client
2019-04-20 17:04:14,602 ERROR    Unhandled exception in thread started by
2019-04-20 17:04:14,602 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 17:04:14,603 ERROR    Traceback (most recent call last):
2019-04-20 17:04:14,603 ERROR      File "<string>", line 3, in recv
2019-04-20 17:04:14,605 ERROR    _bluetooth
2019-04-20 17:04:14,606 ERROR    .
2019-04-20 17:04:14,606 ERROR    error
2019-04-20 17:04:14,607 ERROR    :
2019-04-20 17:04:14,607 ERROR    (104, 'Connection reset by peer')
2019-04-20 17:04:14,608 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 17:04:14,609 ERROR    Traceback (most recent call last):
2019-04-20 17:04:14,609 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 17:04:14,611 ERROR    data = conn.recv(1024)
2019-04-20 17:04:14,612 ERROR      File "<string>", line 5, in recv
2019-04-20 17:04:14,613 ERROR    bluetooth.btcommon
2019-04-20 17:04:14,614 ERROR    .
2019-04-20 17:04:14,614 ERROR    BluetoothError
2019-04-20 17:04:14,615 ERROR    :
2019-04-20 17:04:14,616 ERROR    (104, 'Connection reset by peer')
2019-04-20 17:08:02,180 INFO     client_sock
2019-04-20 17:08:02,181 INFO     <bluetooth.bluez.BluetoothSocket object at 0x709e8d30>
2019-04-20 17:08:02,181 INFO     client_info
2019-04-20 17:08:02,182 INFO     ('F0:0F:EC:1F:89:8E', 1)
2019-04-20 17:08:02,183 INFO     slept enough
2019-04-20 17:08:02,184 INFO     Waiting for RFCOMM connection!!!
2019-04-20 17:08:02,503 INFO     Entered threaded client
2019-04-20 17:08:02,503 ERROR    Unhandled exception in thread started by
2019-04-20 17:08:02,504 ERROR    <function threaded_bt at 0x709ca300>
2019-04-20 17:08:02,505 ERROR    Traceback (most recent call last):
2019-04-20 17:08:02,505 ERROR      File "<string>", line 3, in recv
2019-04-20 17:08:02,507 ERROR    _bluetooth
2019-04-20 17:08:02,507 ERROR    .
2019-04-20 17:08:02,508 ERROR    error
2019-04-20 17:08:02,508 ERROR    :
2019-04-20 17:08:02,509 ERROR    (104, 'Connection reset by peer')
2019-04-20 17:08:02,509 ERROR    
During handling of the above exception, another exception occurred:
2019-04-20 17:08:02,510 ERROR    Traceback (most recent call last):
2019-04-20 17:08:02,510 ERROR      File "uus.py", line 204, in threaded_bt
2019-04-20 17:08:02,512 ERROR    data = conn.recv(1024)
2019-04-20 17:08:02,513 ERROR      File "<string>", line 5, in recv
2019-04-20 17:08:02,514 ERROR    bluetooth.btcommon
2019-04-20 17:08:02,515 ERROR    .
2019-04-20 17:08:02,515 ERROR    BluetoothError
2019-04-20 17:08:02,516 ERROR    :
2019-04-20 17:08:02,516 ERROR    (104, 'Connection reset by peer')
