2019-04-19 06:44:23,366 INFO     setup_logging done
2019-04-19 06:44:33,449 ERROR    Traceback (most recent call last):
2019-04-19 06:44:33,450 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-19 06:44:33,456 ERROR    protocols)
2019-04-19 06:44:33,457 ERROR    _bluetooth
2019-04-19 06:44:33,458 ERROR    .
2019-04-19 06:44:33,458 ERROR    error
2019-04-19 06:44:33,459 ERROR    :
2019-04-19 06:44:33,459 ERROR    (2, 'No such file or directory')
2019-04-19 06:44:33,460 ERROR    
During handling of the above exception, another exception occurred:
2019-04-19 06:44:33,460 ERROR    Traceback (most recent call last):
2019-04-19 06:44:33,461 ERROR      File "uus.py", line 207, in <module>
2019-04-19 06:44:33,463 ERROR    main()
2019-04-19 06:44:33,463 ERROR      File "uus.py", line 139, in main
2019-04-19 06:44:33,465 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-19 06:44:33,466 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-19 06:44:33,468 ERROR    raise BluetoothError (str (e))
2019-04-19 06:44:33,469 ERROR    bluetooth.btcommon
2019-04-19 06:44:33,469 ERROR    .
2019-04-19 06:44:33,470 ERROR    BluetoothError
2019-04-19 06:44:33,470 ERROR    :
2019-04-19 06:44:33,471 ERROR    (2, 'No such file or directory')
2019-04-19 06:44:33,472 ERROR    Exception ignored in:
2019-04-19 06:44:33,473 ERROR    <__main__.LoggerHelper object at 0x756bc450>
2019-04-19 06:44:33,474 ERROR    AttributeError
2019-04-19 06:44:33,475 ERROR    :
2019-04-19 06:44:33,475 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-19 06:48:44,904 INFO     setup_logging done
2019-04-19 06:48:54,988 ERROR    Traceback (most recent call last):
2019-04-19 06:48:54,989 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-19 06:48:54,992 ERROR    protocols)
2019-04-19 06:48:54,993 ERROR    _bluetooth
2019-04-19 06:48:54,993 ERROR    .
2019-04-19 06:48:54,994 ERROR    error
2019-04-19 06:48:54,995 ERROR    :
2019-04-19 06:48:54,995 ERROR    (2, 'No such file or directory')
2019-04-19 06:48:54,996 ERROR    
During handling of the above exception, another exception occurred:
2019-04-19 06:48:54,997 ERROR    Traceback (most recent call last):
2019-04-19 06:48:54,997 ERROR      File "uus.py", line 207, in <module>
2019-04-19 06:48:54,999 ERROR    main()
2019-04-19 06:48:55,000 ERROR      File "uus.py", line 139, in main
2019-04-19 06:48:55,002 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-19 06:48:55,003 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-19 06:48:55,005 ERROR    raise BluetoothError (str (e))
2019-04-19 06:48:55,006 ERROR    bluetooth.btcommon
2019-04-19 06:48:55,006 ERROR    .
2019-04-19 06:48:55,007 ERROR    BluetoothError
2019-04-19 06:48:55,008 ERROR    :
2019-04-19 06:48:55,008 ERROR    (2, 'No such file or directory')
2019-04-19 06:48:55,009 ERROR    Exception ignored in:
2019-04-19 06:48:55,011 ERROR    <__main__.LoggerHelper object at 0x756144d0>
2019-04-19 06:48:55,012 ERROR    AttributeError
2019-04-19 06:48:55,012 ERROR    :
2019-04-19 06:48:55,013 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-19 06:52:09,409 INFO     setup_logging done
2019-04-19 06:52:19,488 ERROR    Traceback (most recent call last):
2019-04-19 06:52:19,489 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-19 06:52:19,492 ERROR    protocols)
2019-04-19 06:52:19,492 ERROR    _bluetooth
2019-04-19 06:52:19,493 ERROR    .
2019-04-19 06:52:19,494 ERROR    error
2019-04-19 06:52:19,495 ERROR    :
2019-04-19 06:52:19,496 ERROR    (2, 'No such file or directory')
2019-04-19 06:52:19,496 ERROR    
During handling of the above exception, another exception occurred:
2019-04-19 06:52:19,497 ERROR    Traceback (most recent call last):
2019-04-19 06:52:19,497 ERROR      File "uus.py", line 207, in <module>
2019-04-19 06:52:19,500 ERROR    main()
2019-04-19 06:52:19,501 ERROR      File "uus.py", line 139, in main
2019-04-19 06:52:19,503 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-19 06:52:19,504 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-19 06:52:19,506 ERROR    raise BluetoothError (str (e))
2019-04-19 06:52:19,507 ERROR    bluetooth.btcommon
2019-04-19 06:52:19,508 ERROR    .
2019-04-19 06:52:19,508 ERROR    BluetoothError
2019-04-19 06:52:19,509 ERROR    :
2019-04-19 06:52:19,510 ERROR    (2, 'No such file or directory')
2019-04-19 06:52:19,511 ERROR    Exception ignored in:
2019-04-19 06:52:19,513 ERROR    <__main__.LoggerHelper object at 0x7567e4d0>
2019-04-19 06:52:19,514 ERROR    AttributeError
2019-04-19 06:52:19,514 ERROR    :
2019-04-19 06:52:19,515 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-19 06:52:30,268 INFO     setup_logging done
2019-04-19 06:52:40,346 ERROR    Traceback (most recent call last):
2019-04-19 06:52:40,348 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-19 06:52:40,350 ERROR    protocols)
2019-04-19 06:52:40,351 ERROR    _bluetooth
2019-04-19 06:52:40,352 ERROR    .
2019-04-19 06:52:40,353 ERROR    error
2019-04-19 06:52:40,354 ERROR    :
2019-04-19 06:52:40,354 ERROR    (2, 'No such file or directory')
2019-04-19 06:52:40,355 ERROR    
During handling of the above exception, another exception occurred:
2019-04-19 06:52:40,356 ERROR    Traceback (most recent call last):
2019-04-19 06:52:40,356 ERROR      File "uus.py", line 207, in <module>
2019-04-19 06:52:40,358 ERROR    main()
2019-04-19 06:52:40,360 ERROR      File "uus.py", line 139, in main
2019-04-19 06:52:40,362 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-19 06:52:40,363 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-19 06:52:40,365 ERROR    raise BluetoothError (str (e))
2019-04-19 06:52:40,366 ERROR    bluetooth.btcommon
2019-04-19 06:52:40,367 ERROR    .
2019-04-19 06:52:40,368 ERROR    BluetoothError
2019-04-19 06:52:40,368 ERROR    :
2019-04-19 06:52:40,369 ERROR    (2, 'No such file or directory')
2019-04-19 06:52:40,371 ERROR    Exception ignored in:
2019-04-19 06:52:40,373 ERROR    <__main__.LoggerHelper object at 0x7568b430>
2019-04-19 06:52:40,373 ERROR    AttributeError
2019-04-19 06:52:40,374 ERROR    :
2019-04-19 06:52:40,375 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-19 06:56:12,176 INFO     setup_logging done
2019-04-19 06:56:22,262 INFO     slept enough
2019-04-19 06:56:22,263 INFO     Waiting for RFCOMM connection!!!
2019-04-19 07:56:15,142 INFO     setup_logging done
2019-04-19 07:56:25,228 INFO     slept enough
2019-04-19 07:56:25,229 INFO     Waiting for RFCOMM connection!!!
